delete from kg_column;


INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (311, 0, '新金融', 'xinjinrong', 3, 0, 121, 1, '金融频道-千氪财经(kg.com)', '金融政策,金融法规,股票债券,保险理财', '千氪财经（kg.com）金融频道汇聚金融行业领袖意见，为广大用户提供金融知识解读,内容涵盖数字货币、股票债券、保险理财、期货信托等，全面解析金融板块相关业务。', '2018-01-05 17:56:04', NULL, '2018-08-10 16:39:45', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (312, 383, '股票期货', 'hangqing', 3, 0, 151, 1, '股票投资-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经股票频道为大家提供最全最新的股票资讯,股市行情,全面解析股市最新动态，并有全天候股票走势分析、要闻点评、大盘分析等。', '2018-01-05 17:56:36', NULL, '2018-01-12 09:55:17', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (319, 0, '区块链', 'shuzihuobi', 3, 0, 1, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (340, 383, '宏观经济', 'hongguan', 3, 0, 131, 1, '宏观经济频道-千氪财经（kg.com）', '国际财经新闻,宏观经济,国际经济大事,财经资讯', '千氪财经(kg.com)宏观经济频道,汇聚最新宏观财经新闻、政策资讯及宏观财经新闻评论,涵盖中国财经新闻、国际财经新闻、国家宏观经济政策信、国内国际经济大事、宏观经济分析、解读。', '2018-01-08 16:48:39', NULL, '2018-04-21 14:34:38', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (341, 0, '理财', 'licai', 2, 0, 100, 1, '理财栏目-千氪财经(kg.com)', '理财,理财产品,投资与理财,如何理财,理财规划,理财师', '千氪财经（kg.com）理财频道，汇聚理财专业资讯，为您提供银行理财、保险理财、基金理财、信托理财、期货理财等领域最新动态，助力个人理财规划。', '2018-01-08 16:48:51', NULL, '2018-01-12 09:55:51', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (343, 0, '基金', 'jijin', 2, 0, 200, 1, '基金理财-千氪财经（kg.com）', '基金买卖,基金申购,基金赎回，基金怎么买,热销基金，基金主题，高收益基金,固定收益基金,基金净值,基金交易,开放式基金,每日基金净值,基金净值估算', '千氪财经（kg.com）基金栏目汇总各大基金理财产品，详细解读各大基金收益，基金回报率，独有的数据分析报告为投资者支招基金怎么买，并有基金买卖，基金申购，基金赎回，基金交易，基金净值估算等专业知识为您解答。', '2018-01-08 16:49:17', NULL, '2018-01-12 09:56:07', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (344, 383, '商业产经', 'chanjing', 3, 0, 161, 1, '产经要闻-千氪财经（kg.com）', '产经要闻,中国产经新闻,产经评论,每日产经新闻,千氪财经（kg.com）', '千氪财经(kg.com)产经要闻频道是报道中国产经相关的新闻，新产经观点，产经相关评论以及每日的产经新闻发布的相关频道，是最快发布产经信息的专业频道之一。', '2018-01-08 16:49:26', NULL, '2018-01-12 09:56:15', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (346, 383, '外汇风向', 'waihui', 3, 0, 141, 1, '外汇频道-千氪财经（kg.com）', '外汇货币,外汇资讯,黄金报价,外汇牌价,外汇行情,外汇走势,经济数据,外汇产品', '千氪财经（kg.com）外汇频道为您提供外汇牌价，外汇资讯，外汇行情和外汇走势等相关信息,并有各类经济数据汇总和外汇产品供你了解。', '2018-01-08 16:49:48', NULL, '2018-01-12 09:57:01', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (348, 0, '期货', 'qihuo', 2, 0, 400, 1, '期货投资-千氪财经（kg.com）', '股指期货,金融期货,金融衍生品,国债期货,利率期货,货币期货,期货产品,期货行情,期货操作技巧,期货资讯', '千氪财经（kg.com）期货投资频道为您提供了期货行情,期货知识,期货报价,期货操作技巧,期货资讯,期货评论等各方面的服务', '2018-01-08 20:22:20', NULL, '2018-03-29 13:24:13', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (349, 0, '商业', 'shangye', 2, 0, 500, 1, '商业资讯-千氪财经（kg.com）', '商业模式,商业投资,商业资讯,商学院,商业案例,商业营销', ' 千氪财经(kg.com)商业资讯频道汇聚商业知识,为你全方位解读商业社会中的那些商业模式及商业案例，深入了解知名商学院，学习深层次商业营销，商业投资知识。', '2018-01-08 16:49:26', NULL, '2018-01-12 09:57:19', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (350, 340, '国内经济', 'guoneijingji', 3, 0, 300, 1, '国内经济要闻-千氪财经（kg.com）', '国内财经资讯,货币政策,央行,风险管控', '千氪财经（kg.com）国内经济要闻涵盖最新国内经济事件，政府风险管控政策,央行最新政策解读,最新的货币政策。', '2018-01-08 16:48:39', NULL, '2018-01-12 09:55:30', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (351, 340, '国际经济', 'guojijingji', 3, 0, 300, 1, '国际财经资讯-千氪财经（kg.com）', '国际财经资讯,美联储,华尔街,国际货币政策', '千氪财经（kg.com）国际财经资讯频道,汇聚最全的的国际财经资讯，掌握一手国际财经走向,了解最新的国际货币政策,华尔街股票最新动态。', '2018-01-08 16:48:39', NULL, '2018-01-12 09:55:40', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (352, 344, '能源', 'nengyuan', 0, 0, 400, 1, '能源频道-千氪财经(kg.com)', '新能源,清洁能源,可再生能源,汽车能源', '千氪财经（kg.com）能源频道汇聚能源相关资讯新闻,关注国内、国际能源发展动态,掌握一手新能源、清洁能源、可再生能源、汽车能源等发展趋势动态。', '2018-01-08 16:49:26', NULL, '2018-01-12 09:56:29', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (353, 344, '商贸', 'shangmao', 0, 0, 400, 1, '商贸频道-千氪财经(kg.com)', '国际贸易,贸易公司,贸易顺差,自由贸易试验区', '千氪财经（kg.com）商贸频道构建商业贸易交流平台，内容涵盖国际贸易、贸易顺差、自由贸易试验区等，更有最新商业、贸易法律法规政策为您解读。', '2018-01-08 16:49:26', NULL, '2018-01-12 09:56:39', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (354, 344, '房地产', 'fangdichan', 0, 0, 400, 1, '地产频道-千氪财经(kg.com)', '房地产税,房价,房价走势,房地产政策法规,房地产成交数据', '千氪财经（kg.com）地产频道为您提供最新的地产资讯、行业新闻，宏观调控的地产价格走势、专题报道，并有详细的房地产最新政策解读、对地产成交数据的分析等。', '2018-01-08 16:49:26', NULL, '2018-01-12 09:56:52', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (355, 349, '创投', 'chuangtou', 3, 0, 25, 1, '创投资讯-千氪财经（kg.com）', ' 创业投资,创业投资项目,风险投资,VC,如何找到风险投资,天使投资', '千氪财经(kg.com)创投频道汇聚最新创业投资资讯，构建投资者与创业项目方的对接平台，更有相关创投知识普及，帮创业者更好的找到适合的创投机构和风险投资。', '2018-01-08 16:49:26', NULL, '2018-01-12 09:57:28', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (356, 349, '管理', 'guanli', 0, 0, 400, 1, '管理知识-千氪财经(kg.com)', '金融管理,管理学,公司管理,管理哲学', '千氪财经(kg.com)管理频道为广大用户提供最完善的金融管理知识,全面普及管理学识，帮助广大身处管理岗位或者对管理岗位充满兴趣的人士在管理技能方面的提高。', '2018-01-08 16:49:26', NULL, '2018-01-12 09:57:41', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (358, 349, '营销', 'yingxiao', 0, 0, 400, 1, '营销频道-千氪财经(kg.com)', '营销策略,营销知识,网络营销知识,营销案例,口碑营销', '千氪财经(kg.com)营销频道全方位打造一站式整合营销服务,为你提供营销知识,实战营销技巧以及品牌营销策略,并有精品营销案例、口碑营销等专业知识供你了解。', '2018-01-08 16:49:26', NULL, '2018-01-12 09:57:54', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (359, 349, '商学院', 'shangxueyuan', 0, 0, 400, 1, '商学院-千氪财经（kg.com）', '知名商学院,长江商学院,MBA,EMBA,EDP,MBA联考,商学院,商界,商业领袖', '千氪财经（kg.com）商学院频道，为您提供国内外最新、最全、最详尽的MBA、EMBA、EDP、中外项目、MBA联考资讯与信息，我们关注中国商学院的教育发展与变革,关注管理模式的发展与创新,关注商学院院校与商界、管理界人物,为商学院与学员之间提供广阔的交流互动平台.', '2018-01-08 16:49:26', NULL, '2018-01-12 09:58:03', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (360, 0, '视频', 'keshipin', 3, 1, 2, 1, '视频-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经股票频道为大家提供最全最新的股票资讯,股市行情,全面解析股市最新动态，并有全天候股票走势分析、要闻点评、大盘分析等。', '2018-01-05 17:56:36', NULL, '2018-05-18 15:25:29', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (361, 383, '政策一览', 'zcyl', 3, 0, 11, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (362, 384, '行业动向', 'hydx', 3, 0, 21, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-08-09 14:25:22', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (364, 383, '行情分析', 'hqfx', 3, 0, 31, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (366, 384, '百家观点', 'bjgd', 3, 0, 41, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (367, 384, '技术动态', 'jsdt', 3, 0, 51, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-08-09 14:26:11', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (369, 383, '项目展示', 'xmzs', 3, 0, 61, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (370, 385, '千氪朝闻', 'qkzw', 3, 0, 71, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-08-09 12:00:54', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (371, 385, '千氪专访', 'qkzf', 3, 0, 81, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-08-09 14:27:05', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (372, 385, '千氪报道', 'qkbd', 3, 0, 91, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (373, 385, '千氪速递', 'qksd', 3, 0, 101, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-08-09 14:27:10', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (374, 385, '千氪观点', 'qkgd', 3, 0, 111, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-08-09 14:27:16', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (375, 387, '版本更新', 'bbgx', 3, 0, 171, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-08-09 14:27:45', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (376, 387, '产品上线预热', 'cpsxyr', 3, 0, 181, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-08-09 14:27:49', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (377, 387, '通知', 'tongzhi', 3, 0, 191, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-08-09 14:27:53', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (378, 387, '奖励公告', 'jlgg', 3, 0, 201, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-08-09 14:27:58', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (379, 0, '百科', 'baike', 3, 0, 8, 1, '百科-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经股票频道为大家提供最全最新的股票资讯,股市行情,全面解析股市最新动态，并有全天候股票走势分析、要闻点评、大盘分析等。', '2018-01-05 17:56:36', NULL, '2018-08-10 16:39:56', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (380, 0, '年中盘点', 'nianzhongpandian', 3, 0, 7, 1, '年中盘点-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经股票频道为大家提供最全最新的股票资讯,股市行情,全面解析股市最新动态，并有全天候股票走势分析、要闻点评、大盘分析等。', '2018-01-05 17:56:36', NULL, '2018-08-02 11:26:17', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (381, 0, '活动', 'huodong', 3, 1, 4, 1, '活动-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经股票频道为大家提供最全最新的股票资讯,股市行情,全面解析股市最新动态，并有全天候股票走势分析、要闻点评、大盘分析等。', '2018-01-05 17:56:36', NULL, '2018-08-10 10:34:17', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (383, 0, '金融', 'jinrong', 3, 1, 0, 1, '金融-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-08-13 16:23:29', NULL, '2018-08-13 16:23:29', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (384, 0, '科技', 'keji', 3, 1, 1, 1, '科技-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-08-13 16:23:29', NULL, '2018-08-13 16:23:29', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (385, 0, '独家', 'dujia', 3, 1, 3, 1, '独家-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-08-13 16:23:29', NULL, '2018-08-13 16:23:29', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (386, 0, '图片', 'tupian', 3, 1, 5, 1, '图片-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-08-13 16:23:29', NULL, '2018-08-13 16:23:29', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (387, 0, '公告', 'gonggao', 3, 1, 6, 1, '公告-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-08-13 16:23:29', NULL, '2018-08-13 16:23:29', NULL, 1);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (389, 384, '区块链', 'qukuailian', 3, 0, 15, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (390, 384, '科技动态', 'kejidongtai', 3, 0, 20, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (392, 360, '交易学堂', 'jiaoyixuetang', 3, 0, 22, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (393, 360, '趣评趣闻', 'qupingquwen', 3, 0, 23, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (395, 360, '新闻播报', 'xinwenbobao', 3, 0, 24, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (396, 360, '行情分析', 'hangqingfenxi', 3, 0, 25, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (397, 360, '微科普', 'weikepu', 3, 0, 26, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (398, 360, '杂谈', 'zatan', 3, 0, 27, 1, '数字资产频道_千氪财经（kg.com）', '数字货币交易平台,虚拟货币价格,比特币交易,比特币价格走势,钛值（TV）交易', '千氪财经（kg.com）数字货币资讯频道，关注最新数字货币走向，数字货币交易平台，虚拟货币交易市场,更为您不间断预报比特币最新价格以及交易走势', '2018-01-08 16:49:58', NULL, '2018-02-08 14:47:21', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (399, 381, '线下活动', 'xianxiahuodong', 3, 0, 32, 1, '活动-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经股票频道为大家提供最全最新的股票资讯,股市行情,全面解析股市最新动态，并有全天候股票走势分析、要闻点评、大盘分析等。', '2018-01-05 17:56:36', NULL, '2018-08-10 10:34:17', NULL, 2);
INSERT INTO `kg_column` (`column_id`, `prev_column`, `column_name`, `column_urlname`, `navigator_display`, `display_status`, `column_order`, `display_mode`, `seo_title`, `seo_keyword`, `seo_description`, `create_date`, `create_user`, `update_date`, `update_user`, `column_level`) VALUES (401, 381, '线上活动', 'xianshanghuodong', 3, 0, 32, 1, '活动-千氪财经（kg.com）', '千氪财经,股票行情,股票机构,股票资讯,美股行情,港股行情', '千氪财经股票频道为大家提供最全最新的股票资讯,股市行情,全面解析股市最新动态，并有全天候股票走势分析、要闻点评、大盘分析等。', '2018-01-05 17:56:36', NULL, '2018-08-10 10:34:17', NULL, 2);


update kg_article set column_id=389 where column_id=369;

update kg_article set second_column=column_id where column_id in (
312, 340, 344, 346, 361, 364, 
362, 366, 367, 389, 390,
392, 393, 395, 396, 397, 398,
370, 371, 372, 373, 374,
399, 401,
375, 376, 377, 378
);

update kg_article set column_id=383 where second_column in 
( 312, 340, 344, 346, 361, 364 );

update kg_article set column_id=384 where second_column in 
( 362, 366, 367, 389, 390 );

update kg_article set column_id=360 where second_column in 
( 392, 393, 395, 396, 397, 398 );

update kg_article set column_id=385 where second_column in 
( 370, 371, 372, 373, 374 );

update kg_article set column_id=381 where second_column in 
( 399, 401 );

update kg_article set column_id=387 where second_column in 
( 375, 376, 377, 378 );
